const GXT_STORE_LIST = [
  "WM+ HGG 178 Đường Nguyễn Trãi",
  "WM+ HGG 43-45 Đường 20-8",
  "WM+ HGG 469 Nguyễn Trãi",
  "WM+ HGG Thôn Vạt, Việt Lâm",
  "WM+ HGG Tổ 1 Đường Nguyễn Trãi, TT Vị Xuyên",
  "WM+ HGG Tổ 6, Nông trường Việt Lâm",
  "WM+ HGG Tổ 8 Vị Xuyên",
  "WM VCP HBH Hòa Bình",
  "WM+ HBH 253 Phùng Hưng",
  "WM+ HBH 444 Cù Chính Lan",
  "WM+ HBH 469 Hoàng Văn Thụ",
  "WM+ HBH 490 Trần Hưng Đạo",
  "WM+ HBH 665 Cù Chính Lan",
  "WM+ HBH 841 An Dương Vương",
  "WM+ HBH Toà Ann House, Tân Thịnh",
  "WM+ HBH Tổ 09 Phường Tân Thịnh",
  "WM+ HBH Tổ 8 Phường Hữu Nghị",
  "WM+ PTO 301-303 Trần Hưng Đạo",
  "WM+ PTO 642-644 Cù Chính Lan",
  "WM+ LCI 02-04 Võ Nguyên Giáp",
  "WM+ LCI 030 Quy Hóa",
  "WM+ LCI 050 Phan Đình Phùng",
  "WM+ LCI 085-086 Nhạc Sơn",
  "WM+ LCI 088 Nhạc Sơn",
  "WM+ LCI 102-104 Cốc Lếu",
  "WM+ LCI 114 Hàm Nghi",
  "WM+ LCI 737 Lê Thanh",
  "WM+ LCI 750 Hoàng Quốc Việt",
  "WM+ LCI Số 003 Soi Tiền",
  "WM+ LCI Số 145 - 147 Nguyễn Huệ",
  "WM+ LCI Số 489 Ngô Quyền",
  "WM+ SLA 17 Đường Lò Văn Giá",
  "WM+ SLA 93-95 đường Cách Mạng Tháng",
  "WM+ SLA Tân Lập, Chiềng Khương",
  "WM+ PTO 58 Hồ Thiên Hương",
  "WM+ PTO Khu 21, Vạn Xuân",
  "WM+ PTO Khu 23 Vạn Xuân",
  "WM VC+ PTO Phú Thọ",
  "WM+ PTO 25 tổ 10 Tân An",
  "WM+ PTO 75 Cao Bang",
  "WM+ PTO An Ninh Hạ, Phú Thọ",
  "WM+ PTO Thanh Bình, Âu Cơ",
  "WM+ SLA Tông Lạnh, Thuận Châu",
  "WM VCP SLA Sơn La",
  "WM+ SLA 124 Tổ 8 Quyết Thắng",
  "WM+ SLA 15 Lê Lợi",
  "WM+ SLA 17 Đường Lò Văn Giá",
  "WM+ SLA 181 Bùi Thị Xuân",
  "WM+ SLA 186 Lê Đức Thọ",
  "WM+ SLA 223 Chu Văn Thịnh",
  "WM+ SLA 274 Trường Chinh",
  "WM+ SLA 437A Trần Đăng Ninh",
  "WM+ SLA 514D Trần Đăng Ninh",
  "WM+ SLA 67 Trường Chinh",
  "WM+ SLA Tổ 8 Chiềng Sinh",
  "WM VCP PTO Việt Trì",
  "WM+ PTO 107 Bạch Hạc",
  "WM+ PTO 12 Tổ 5 Trần Phú",
  "WM+ PTO 1250 Hùng Vương",
  "WM+ PTO 130 Lê Quý Đôn",
  "WM+ PTO 1343 Hùng Vương",
  "WM+ PTO 167-169 Nguyễn Trãi",
  "WM+ PTO 188 Đường Nam, Phù Ninh",
  "WM+ PTO 191 Cao Du",
  "WM+ PTO 192-194 Trần Phú, Việt Trì",
  "WM+ PTO 235-235B TT Hùng Sơn",
  "WM+ PTO 26 Âu Cơ",
  "WM+ PTO 3023 Đại Lộ Hùng Vương",
  "WM+ PTO 35 Hà Chương",
  "WM+ PTO 439 Tiên Dung",
  "WM+ PTO 44 Nguyễn Du",
  "WM+ PTO 44 Đại Nải",
  "WM+ PTO 476 Châu Phong",
  "WM+ PTO 545 Trần Phú",
  "WM+ PTO 62 Phan Châu Trinh",
  "WM+ PTO 66 Hàn Thuyên",
  "WM+ PTO 73 Quang Trung",
  "WM+ PTO Băng 1, Nguyễn Tất Thành",
  "WM+ PTO Băng 1, Quang Trung",
  "WM+ PTO Cao Xá, Lâm Thao",
  "WM+ PTO Khu 1, Bản Nguyên",
  "WM+ PTO Khu 10, Xuân Lũng",
  "WM+ PTO Khu 12 Phú Hộ",
  "WM+ PTO Khu 12, TT Lâm Thao",
  "WM+ PTO Khu 15, Dục Mỹ",
  "WM+ PTO Khu 2, Xuân Lũng",
  "WM+ PTO Khu 2A, Nông Trang",
  "WM+ PTO Khu 3 Hùng Lô, Việt Trì",
  "WM+ PTO Khu 3 Vân Phú",
  "WM+ PTO Khu 3, TT Phong Châu",
  "WM+ PTO Khu 5 Nông Trang",
  "WM+ PTO Khu 5, Tứ Xã",
  "WM+ PTO Khu 6, Hy Cương",
  "WM+ PTO Khu 6B, Nông Trang",
  "WM+ PTO Khu 8 Nông Trang",
  "WM+ PTO Khu Km5, Hà Lộc",
  "WM+ PTO Khu Trung Phương, Việt Trì",
  "WM+ PTO Khu Tân An, Tân Dân",
  "WM+ PTO Khu Tân Thịnh, Tân Dân",
  "WM+ PTO Núi Trang, Phù Ninh",
  "WM+ PTO Thành Công, Việt Trì",
  "WM+ PTO Tổ 1, khu 1A, Vân Phú",
  "WM+ PTO Tổ 26A Hai Bà Trưng",
  "WM+ PTO Vũ Duệ, Việt Trì",
  "WM+ PTO Đồng Gia, Việt Trì",
  "WM+ PTO Đội 3, Nông Trang",
  "WM+ PTO Khu 9, Chí Tiên",
  "WM+ PTO Bình Phú, Phù Ninh",
  "WM+ PTO Khu 10, Phù Ninh",
  "WM+ PTO Khu 2, Trạm Thản",
  "WM+ PTO Khu 4, Phú Mỹ",
  "WM+ PTO Phú Lộc, Phù Ninh",
  "WM VCP TQG Tuyên Quang",
  "WM+ TQG 10 Lê Duẩn P.Phan Thiết",
  "WM+ TQG 102 Phan Thiết",
  "WM+ TQG 11 - 13 Trường Chinh",
  "WM+ TQG 218 Lê Duẩn",
  "WM+ TQG 288 đường 17/8",
  "WM+ TQG 328 Trường Chinh",
  "WM+ TQG 347 Phạm Văn Đồng",
  "WM+ TQG Lập Thành, Mỹ Bằng",
  "WM+ TQG TDP Chè Đen 1",
  "WM+ TQG TDP Lang Quán, Yên Sơn",
  "WM+ TQG Thôn 1 Đội Cấn",
  "WM+ TQG Thôn 4, Lưỡng Vượng",
  "WM+ TQG Tổ 16 phường Tân Quang",
  "WM+ TQG Tổ 4 Phường Nông Tiến",
  "WM+ TQG Xóm 8 xã Trung Môn",
  "WM+ TQG Đức Hùng Plaza",
  "WM VCP YBI Yên Bái",
  "WM+ YBI 070 Ngô Minh Loan",
  "WM+ YBI 1016 Yên Ninh",
  "WM+ YBI 102 Đại Lộ Nguyễn Thái Học",
  "WM+ YBI 111 Nguyễn Tất Thành",
  "WM+ YBI 1132 Đinh Tiên Hoàng",
  "WM+ YBI 12 Lê Hồng Phong",
  "WM+ YBI 142 Đinh Tiên Hoàng",
  "WM+ YBI 150A Đường Hoàng Hoa Thám",
  "WM+ YBI 326 Điện Biên",
  "WM+ YBI 352 Đường Đại Đồng-Yên Bình",
  "WM+ YBI 385 Lê Hồng Phong, Nguyễn P",
  "WM+ YBI 486 Đinh Tiên Hoàng",
  "WM+ YBI 525 Đại Lộ Nguyễn Thái Học",
  "WM+ YBI 551 Điện Biên",
  "WM+ YBI 64 Phạm Văn Đồng",
  "WM+ YBI 701 Đại Đồng",
  "WM+ YBI Số 2 Quang Trung-Đồng Tâm",
  "WM+ LCI 158-160 Quang Trung",
  "WM+ LCI 59 Thôn Lương An",
  "WM+ PTO 77 Khu Tâm Đức",
  "WM+ TQG 205 Võ Chí Công",
  "VM+ TQG 88 Trần Hưng Đạo",
  "VinMart Yên Bái"
];
